name: 'inteligencia_expansao_educacional'
version: '1.0.0'
config-version: 2

profile: 'inteligencia_expansao_educacional'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  inteligencia_expansao_educacional:
    +materialized: table
    raw:
      +materialized: view
      +tags: ['raw']
    staging:
      +materialized: view
      +tags: ['staging']
      +schema: staging
    dimensions:
      +materialized: table
      +schema: dimensions
      +tags: ['dimensions']
    facts:
      +materialized: table
      +schema: facts
      +tags: ['facts']

seeds:
  inteligencia_expansao_educacional:
    +quote_columns: false
    fgv_cursos_competidores:
      +schema: fgv_internal
      +column_types:
        co_uf: integer
        co_curso: integer
        co_ies: integer
    fgv_depara:
      +schema: staging
      +column_types:
        co_uf: integer
        co_ies: integer
        co_curso: integer

vars:
  'data_project': 'inteligencia_expansao_educacional'
  'raw_database': 'raw'
