inteligencia_expansao_educacional:
  outputs:
    dev:
      type: bigquery
      project: project-a8f8452a-3033-4dd8-99a
      dataset: raw
      location: US
      method: oauth
      threads: 4
      timeout_seconds: 300
      priority: interactive
  target: dev
