version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: inep_graduacao
      - name: inse_escola
      - name: ideb_escola
      - name: inep_formandos_ensinomedio
      - name: rais_vinculos_municipio
